const { NextResponse } = require('next/server');
const { parseUploadedDocument } = require('../../../services/vertex');

// Set dynamic configuration to ensure request parses correctly
export const dynamic = 'force-dynamic';

export async function POST(request) {
  try {
    const contentType = request.headers.get('content-type') || '';
    
    if (contentType.includes('multipart/form-data')) {
      const formData = await request.formData();
      const file = formData.get('file');
      
      if (!file) {
        return NextResponse.json({ error: 'No file uploaded' }, { status: 400 });
      }
      
      const arrayBuffer = await file.arrayBuffer();
      const buffer = Buffer.from(arrayBuffer);
      const mimeType = file.type || 'image/jpeg';
      
      // Parse file using Vertex AI
      const extractedData = await parseUploadedDocument(buffer, mimeType);
      
      // Add a client-side generated UUID if not generated by model
      extractedData.id = `REC-${Math.floor(1000 + Math.random() * 9000)}`;
      
      return NextResponse.json({ data: extractedData });
    } else {
      // Handle JSON body if text is passed directly
      const body = await request.json();
      const textDescription = body.text;
      
      if (!textDescription) {
        return NextResponse.json({ error: 'No input provided' }, { status: 400 });
      }
      
      // Convert text to a buffer for parsing, using text/plain mime type
      const buffer = Buffer.from(textDescription, 'utf-8');
      const extractedData = await parseUploadedDocument(buffer, 'text/plain');
      extractedData.id = `REC-${Math.floor(1000 + Math.random() * 9000)}`;
      
      return NextResponse.json({ data: extractedData });
    }
  } catch (error) {
    console.error('API Error in /api/upload:', error);
    return NextResponse.json({ 
      error: 'Failed to process document', 
      details: error.message 
    }, { status: 500 });
  }
}
